<?php
require __DIR__.'/../_header_admin.php';
$escape=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$queryBase=$_GET;$queryBase['action']='retention_history';unset($queryBase['page']);
$pageUrl=static fn(int $page):string=>APP_URL.'/index.php?'.http_build_query($queryBase+['page'=>$page]);
?>
<main class="flex-1 min-w-0 bg-[#f7f7f8] px-3 py-6 sm:px-6 lg:px-8"><section class="mx-auto max-w-6xl"><a href="<?=APP_URL?>/index.php?action=retention" class="text-sm font-bold text-indigo-700 hover:underline">← Volver a Retención</a><header class="mt-4"><h1 class="text-2xl font-extrabold text-neutral-950 sm:text-3xl">Historial de asistencia</h1><p class="mt-2 text-sm text-neutral-600">Visitas únicas por socio y día. Los reintentos técnicos no inflan el historial.</p></header>
<?php if($filterError!==null):?><div role="alert" class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-950"><?=$escape($filterError)?> Se muestra el historial sin filtros.</div><?php endif;?>
<form method="GET" action="<?=APP_URL?>/index.php" class="mt-6 grid gap-3 rounded-3xl border border-neutral-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="action" value="retention_history"><div><label for="history-from" class="mb-1 block text-xs font-bold text-neutral-600">Desde</label><input id="history-from" type="date" name="from" value="<?=$escape($filters['from'])?>" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"></div><div><label for="history-to" class="mb-1 block text-xs font-bold text-neutral-600">Hasta</label><input id="history-to" type="date" name="to" value="<?=$escape($filters['to'])?>" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"></div><div><label for="history-activity" class="mb-1 block text-xs font-bold text-neutral-600">Actividad</label><select id="history-activity" name="activity" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"><option value="">Todas</option><?php foreach(['GYM'=>'Gym','BOXEO'=>'Boxeo','TATAMI'=>'Tatami','GENERAL'=>'General'] as $value=>$label):?><option value="<?=$value?>" <?=$filters['activity']===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div><label for="history-member" class="mb-1 block text-xs font-bold text-neutral-600">Socio</label><input id="history-member" name="member" maxlength="100" value="<?=$escape($filters['member'])?>" placeholder="Nombre o apellidos" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"></div><?php if($sites!==[]):?><div><label for="history-site" class="mb-1 block text-xs font-bold text-neutral-600">Sede</label><select id="history-site" name="site" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"><option value="0">Todas las sedes</option><?php foreach($sites as $site):?><option value="<?=(int)$site['id_gimnasio']?>" <?=$selectedSite===(int)$site['id_gimnasio']?'selected':''?>><?=$escape($site['nombre'])?></option><?php endforeach;?></select></div><?php endif;?><button type="submit" class="min-h-11 rounded-xl bg-[#111318] px-6 text-sm font-bold text-white sm:col-span-2 lg:col-span-5 lg:justify-self-start">Aplicar filtros</button></form>
<div class="mt-6 flex items-center justify-between"><p class="text-sm font-bold text-neutral-700"><?=(int)$pagination['total']?> visita<?=((int)$pagination['total']===1?'':'s')?> única<?=((int)$pagination['total']===1?'':'s')?></p><p class="text-xs text-neutral-500">Página <?=(int)$pagination['page']?> de <?=(int)$pagination['pages']?></p></div>
<?php if($visits===[]):?><div class="mt-4 rounded-3xl border border-dashed border-neutral-300 bg-white p-12 text-center text-sm text-neutral-500">No hay asistencias con estos filtros.</div><?php else:?><div class="mt-4 overflow-hidden rounded-3xl border border-neutral-200 bg-white"><ol class="divide-y divide-neutral-100"><?php foreach($visits as $visit):?><li class="grid gap-1 p-4 sm:grid-cols-[150px_1fr_120px_1fr] sm:items-center"><time class="text-sm font-extrabold text-neutral-800"><?=$escape($visit['local_datetime'])?></time><span class="text-sm font-semibold text-neutral-950"><?=$escape(trim($visit['nombre'].' '.$visit['apellidos']))?></span><span class="text-xs font-bold text-neutral-600"><?=$escape($visit['activity_label'])?></span><span class="text-xs text-neutral-500 sm:text-right"><?=$escape($visit['sede_nombre'])?></span></li><?php endforeach;?></ol></div><?php endif;?>
<?php if($pagination['pages']>1):?><nav aria-label="Paginación del historial" class="mt-6 flex flex-wrap justify-center gap-2"><?php if($pagination['page']>1):?><a class="inline-flex min-h-11 items-center rounded-xl border border-neutral-300 bg-white px-4 text-sm font-bold" href="<?=$escape($pageUrl($pagination['page']-1))?>">Anterior</a><?php endif;?><?php if($pagination['page']<$pagination['pages']):?><a class="inline-flex min-h-11 items-center rounded-xl border border-neutral-300 bg-white px-4 text-sm font-bold" href="<?=$escape($pageUrl($pagination['page']+1))?>">Siguiente</a><?php endif;?></nav><?php endif;?>
</section></main></div><?php require __DIR__.'/../_footer.php';?>
