<?php
require __DIR__.'/../_header_admin.php';
$escape=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$queryBase=$_GET;$queryBase['action']='retention_cases';unset($queryBase['page'],$queryBase['ok'],$queryBase['err']);
$pageUrl=static fn(int $page):string=>APP_URL.'/index.php?'.http_build_query($queryBase+['page'=>$page]);
$selectedState=in_array($filters['state'],['attention','high','partial','returned','normal','insufficient','all'],true)?$filters['state']:'attention';
?>
<main class="flex-1 min-w-0 bg-[#f7f7f8] px-3 py-6 sm:px-6 lg:px-8"><section class="mx-auto max-w-6xl"><a href="<?=APP_URL?>/index.php?action=retention" class="text-sm font-bold text-indigo-700 hover:underline">← Volver a Retención</a><header class="mt-4"><h1 class="text-2xl font-extrabold text-neutral-950 sm:text-3xl">Todos los estados de retención</h1><p class="mt-2 text-sm text-neutral-600">Listado paginado dentro de tu empresa y sedes autorizadas.</p></header>
<?php if(!empty($_GET['ok'])):?><div role="status" class="mt-5 rounded-2xl border border-green-200 bg-green-50 p-4 text-sm font-bold text-green-900"><?=$escape($_GET['ok'])?></div><?php endif;?><?php if(!empty($_GET['err'])):?><div role="alert" class="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-900"><?=$escape($_GET['err'])?></div><?php endif;?>
<form method="GET" action="<?=APP_URL?>/index.php" class="mt-6 grid gap-3 rounded-3xl border border-neutral-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><input type="hidden" name="action" value="retention_cases"><div><label for="filter-state" class="mb-1 block text-xs font-bold text-neutral-600">Estado</label><select id="filter-state" name="state" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"><?php foreach(['attention'=>'Necesitan atención','high'=>'Hace tiempo que no vienen','partial'=>'Rutina a medias','returned'=>'Han vuelto','normal'=>'Siguen su rutina','insufficient'=>'Conociendo su rutina','all'=>'Todos'] as $value=>$label):?><option value="<?=$value?>" <?=$selectedState===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div><label for="filter-activity" class="mb-1 block text-xs font-bold text-neutral-600">Actividad</label><select id="filter-activity" name="activity" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"><option value="">Todas</option><?php foreach(['GYM'=>'Gym','BOXEO'=>'Boxeo','TATAMI'=>'Tatami','GENERAL'=>'General'] as $value=>$label):?><option value="<?=$value?>" <?=strtoupper($filters['activity'])===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div><label for="filter-workflow" class="mb-1 block text-xs font-bold text-neutral-600">Seguimiento</label><select id="filter-workflow" name="workflow" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"><option value="">Todos</option><?php foreach(['pending'=>'Pendiente','reviewed'=>'Revisado','postponed'=>'Pospuesto','contacted'=>'Contactado','dismissed'=>'Descartado','returned'=>'Ha vuelto'] as $value=>$label):?><option value="<?=$value?>" <?=strtolower($filters['workflow'])===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><?php if($sites!==[]):?><div><label for="filter-site" class="mb-1 block text-xs font-bold text-neutral-600">Sede</label><select id="filter-site" name="site" class="min-h-11 w-full rounded-xl border border-neutral-300 px-3 text-sm"><option value="0">Todas las sedes</option><?php foreach($sites as $site):?><option value="<?=(int)$site['id_gimnasio']?>" <?=$selectedSite===(int)$site['id_gimnasio']?'selected':''?>><?=$escape($site['nombre'])?></option><?php endforeach;?></select></div><?php endif;?><button type="submit" class="min-h-11 rounded-xl bg-[#111318] px-6 text-sm font-bold text-white sm:col-span-2 lg:col-span-4 lg:justify-self-start">Aplicar filtros</button></form>
<div class="mt-6 flex items-center justify-between"><p class="text-sm font-bold text-neutral-700"><?=(int)$pagination['total']?> socio<?=((int)$pagination['total']===1?'':'s')?></p><p class="text-xs text-neutral-500">Página <?=(int)$pagination['page']?> de <?=(int)$pagination['pages']?></p></div>
<?php if($cases===[]):?><div class="mt-4 rounded-3xl border border-dashed border-neutral-300 bg-white p-12 text-center text-sm text-neutral-500">No hay resultados con estos filtros.</div><?php else:?><div class="mt-4 space-y-4"><?php foreach($cases as $item):?><?php if(in_array($item['display_state'],['ATTENTION','HIGH_ATTENTION'],true)):?><?php $returnTo='retention_cases';require __DIR__.'/retention_case_card.php';?><?php else:?><article class="rounded-2xl border border-neutral-200 bg-white p-4 sm:p-5"><div class="flex flex-wrap items-center justify-between gap-2"><div><h2 class="font-extrabold text-neutral-950"><?=$escape(trim($item['nombre'].' '.$item['apellidos']))?></h2><p class="mt-1 text-xs text-neutral-500"><?=$escape($item['sede_nombre'])?> · <?=$escape($item['activity_label'])?></p></div><span class="rounded-full bg-neutral-100 px-3 py-1 text-xs font-bold text-neutral-800"><?=$escape($item['state_label'])?></span></div><p class="mt-3 text-sm text-neutral-700"><?=$escape($item['explanation'])?></p><?php if($item['display_state']==='RETURNED'):?><p class="mt-2 text-sm text-neutral-600">Regreso: <?=$escape($item['returned_label'])?><?php if($item['days_to_return']!==null):?> · <?=(int)$item['days_to_return']?> días desde la detección<?php endif;?></p><?php else:?><p class="mt-2 text-xs text-neutral-500">Última asistencia: <?=$escape($item['last_attendance_label'])?></p><?php endif;?></article><?php endif;?><?php endforeach;?></div><?php endif;?>
<?php if($pagination['pages']>1):?><nav aria-label="Paginación de estados" class="mt-6 flex flex-wrap justify-center gap-2"><?php if($pagination['page']>1):?><a class="inline-flex min-h-11 items-center rounded-xl border border-neutral-300 bg-white px-4 text-sm font-bold" href="<?=$escape($pageUrl($pagination['page']-1))?>">Anterior</a><?php endif;?><?php if($pagination['page']<$pagination['pages']):?><a class="inline-flex min-h-11 items-center rounded-xl border border-neutral-300 bg-white px-4 text-sm font-bold" href="<?=$escape($pageUrl($pagination['page']+1))?>">Siguiente</a><?php endif;?></nav><?php endif;?>
</section></main></div><?php require __DIR__.'/../_footer.php';?>
